#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         String-SetUTF8
version:      1.00
version_from: SetUTF8.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
